version: "3"
services:
  web:
    image: ioet/bpm-projects-api:latest
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 400M
      restart_policy:
        condition: on-failure
    ports:
      - "8000:80"
    networks:
      - ioet-bpm-projects-subnet
networks:
  ioet-bpm-projects-subnet: